spring:
  config:
    import:
      - 'classpath:adapter-http-property.yml'
      - 'classpath:adapter-persistence-property.yml'
      - 'classpath:adapter-redis-property.yml'
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: dcdf9398ec1f51f893be448a8f11d92b # 카카오 REST API 키
            client-secret: 8n4zV6Fsj8pysvjt2bYlCvjIA5WbvXhf # 카카오 Client Secret Code
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:3000/login/oauth2/code/kakao" # 카카오 Redirect URI
            scope: profile_nickname
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret: 281d0a7da2bdea133dd16fbb15848282e3635d8bc6c2e5f8b3d0c4c8332b284e # JWT Secret Key(openssl rand -hex 32 생성)
  expire:
    access-token: 1
    refresh-token: 24